# Generated by Django 6.1 on 2026-09-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentcourse',
            name='unique_student_course',
        ),
    ]
