# Generated by Django 6.1 on 2026-10-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo')], default='ACTIVO', max_length=8),
        ),
    ]
